# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name boot_ardl_c
#' @title Code to generate data having a VECM-ARDL structure
#' @param r_in input residuals
#' @param GAMMAX short run parameter matrices column bound, first row in conditional form
#' @param A long-run parameter matrix, first row in conditional form
#' @param start_z data matrix of starting point
#' @param omegat parameter vector of the unlagged differences
#' @param interc vecm intercept, first element in conditional form
#' @param trend vecm trend, first element in conditional form
#' @return A list containing the generated dataset
#' @keywords internal
NULL

boot_ardl_c <- function(r_in, GAMMAX, A, start_z, omegat, interc, trend) {
    .Call(`_bootCT_boot_ardl_c`, r_in, GAMMAX, A, start_z, omegat, interc, trend)
}

